package com.example.mahilashaktiunnati.util

import com.example.mahilashaktiunnati.data.local.LoanStatus
import com.example.mahilashaktiunnati.data.local.entity.LoanEntity
import com.example.mahilashaktiunnati.data.local.entity.MemberEntity
import com.example.mahilashaktiunnati.data.local.entity.SavingsEntity

/**
 * Generates formatted text reports for sharing via WhatsApp or other apps.
 */
object ReportGenerator {

    /**
     * Generate a complete group financial report.
     */
    fun generateGroupReport(
        members: List<MemberEntity>,
        savings: List<SavingsEntity>,
        loans: List<LoanEntity>,
        totalSavings: Double,
        totalLoansGiven: Double,
        totalInterestEarned: Double
    ): String {
        val activeLoans = loans.count { it.status == LoanStatus.ACTIVE }
        val closedLoans = loans.count { it.status == LoanStatus.CLOSED }
        val pendingLoans = loans.count { it.status == LoanStatus.PENDING_APPROVAL }
        val totalRepaid = loans.sumOf { it.amountRepaid }

        return buildString {
            appendLine("═══════════════════════════════")
            appendLine("  *Mahila-Shakti Unnati*")
            appendLine("  *Group Financial Report*")
            appendLine("═══════════════════════════════")
            appendLine()
            appendLine("📊 *Summary*")
            appendLine("──────────────────────────")
            appendLine("👥 Total Members: ${members.size}")
            appendLine("💰 Total Group Savings: ${FinancialUtils.formatCurrencyShort(totalSavings)}")
            appendLine("🏦 Total Loans Given: ${FinancialUtils.formatCurrencyShort(totalLoansGiven)}")
            appendLine("📈 Interest Earned: ${FinancialUtils.formatCurrencyShort(totalInterestEarned)}")
            appendLine("💳 Total Repaid: ${FinancialUtils.formatCurrencyShort(totalRepaid)}")
            appendLine()
            appendLine("📋 *Loan Status*")
            appendLine("──────────────────────────")
            appendLine("🟢 Active Loans: $activeLoans")
            appendLine("✅ Closed Loans: $closedLoans")
            appendLine("🟡 Pending Approval: $pendingLoans")
            appendLine()
            appendLine("──────────────────────────")
            appendLine("Generated by Mahila-Shakti Unnati")
            appendLine("_Empowering Women Through_")
            appendLine("_Financial Independence_")
        }
    }

    /**
     * Generate a member-specific savings report.
     */
    fun generateMemberSavingsReport(
        member: MemberEntity,
        savings: List<SavingsEntity>,
        totalSavings: Double
    ): String {
        return buildString {
            appendLine("*Savings Report - ${member.fullName}*")
            appendLine("Member ID: ${member.memberId}")
            appendLine("──────────────────────────")
            appendLine("Total Savings: ${FinancialUtils.formatCurrencyShort(totalSavings)}")
            appendLine("Total Entries: ${savings.size}")
            appendLine()
            savings.take(10).forEach { entry ->
                val status = if (entry.status.name == "PAID") "✅" else "⏳"
                appendLine("$status ${FinancialUtils.formatDate(entry.paymentDate)} - ${FinancialUtils.formatCurrencyShort(entry.amountPaid)}")
            }
            if (savings.size > 10) {
                appendLine("... and ${savings.size - 10} more entries")
            }
        }
    }

    /**
     * Generate a loan summary report.
     */
    fun generateLoanSummaryReport(
        loans: List<LoanEntity>,
        memberNames: Map<String, String>
    ): String {
        return buildString {
            appendLine("*Loan Summary Report*")
            appendLine("═══════════════════════════════")
            appendLine()
            loans.forEach { loan ->
                val memberName = memberNames[loan.memberId] ?: "Unknown"
                val statusEmoji = when (loan.status) {
                    LoanStatus.ACTIVE -> "🟢"
                    LoanStatus.CLOSED -> "✅"
                    LoanStatus.PENDING_APPROVAL -> "🟡"
                }
                appendLine("$statusEmoji *$memberName*")
                appendLine("   Amount: ${FinancialUtils.formatCurrencyShort(loan.loanAmount)}")
                appendLine("   Rate: ${loan.interestRate}% p.a.")
                appendLine("   Remaining: ${FinancialUtils.formatCurrencyShort(loan.remainingBalance)}")
                appendLine("   Status: ${loan.status.name.replace("_", " ")}")
                appendLine()
            }
        }
    }
}
